/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as users from "../users.js";
import type * as attendance from "../attendance.js";
import type * as leaves from "../leaves.js";
import type * as payroll from "../payroll.js";
import type * as performance from "../performance.js";
import type * as interviews from "../interviews.js";
import type * as candidates from "../candidates.js";
import type * as notifications from "../notifications.js";
import type * as ai from "../ai.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  users: typeof users;
  attendance: typeof attendance;
  leaves: typeof leaves;
  payroll: typeof payroll;
  performance: typeof performance;
  interviews: typeof interviews;
  candidates: typeof candidates;
  notifications: typeof notifications;
  ai: typeof ai;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;